### ISSUE TITLE
Crossfade app name change

### ISSUE THREAD

**Issue by Skaldebane** [fthx/appmenu-is-back#5]
When the title is added or removed (e.g. by opening/closing a new app or navigating to a different workspace), it has a subtle fade animation.

However, if the app changes, the title snaps to the new title. While it may be fine when alt-tabbing, it looks a bit abrupt when switching workspaces. Adding a crossfade animation when the title changes would make it look a bit nicer.

And thanks for this amazing extension!

**Comment by fthx** [comment]
Sorry but I did not plan to maintain this official GNOME extension except for compatibility.
In Windows Title Is Back extension, I can think to this.

**Comment by Skaldebane** [comment]
Ah alright, I opened the same issue there: https://github.com/fthx/window-title-is-back/issues/15

**Comment by fthx** [comment]
Great. Sorry for that but I just adapted this extension to match the old GNOME feature. I do not even use it!
I go to Window Title now.
