### ISSUE TITLE
I love it; but improvements are possible...

### ISSUE THREAD

**Issue by ishnath** [fthx/appmenu-is-back#6]
Possible improvements:

1) For some reason, which only you can figure out, the extension doesn't work after an OS reboot. I have to start the gnome-extensions-app, and disable-enable the appmenu-is-back extension, every-time I start the OS. This, of course, is a drawback that needs to be eradicated, but I happily start the gnome-extensions-app, and disable-enable the appmenu-is-back extension, every-time I start the OS. It's better for me than not having the old app-menu at all, in gnome shell 45+.

2) The SuperKey+F10 keyboard shortcut doesn't work. It can work, after the makers of this extension improve this extension, to make it work, if they do do so, ever. Until it starts working, I have this suggestion: instead of SuperKey+F10, use SuperKey+v followed by the left-side-arrow-key.

Thanks; and keep up the good work, for the benefit of other linux users, who, like you, prefer to have the OS work differently than it does, by default.

**Comment by fthx** [comment]
Hi,

I've exported this old official GNOME extension but I won't update/develop it.
Sorry!
